#!/usr/bin/env bash
# Installs HAProxy version 1.8

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
#apt-get install -y haproxy=1.8.\*


echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

echo "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 531192-web-01 54.237.43.101:80 check
    server 531192-web-02  100.25.156.252:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy start
