#!/usr/bin/env bash
# manage processes named my_process

file="/var/run/my_process.pid"
command="$1"

if [ "$command" == "start" ]; then
  bash ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$command" == "stop" ]; then
  [ -e "$file" ] && pkill -f './manage_my_process' && rm "$file"
  echo "manage_my_process stopped"

elif [ "$command" == "restart" ]; then

  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}" 
fi
