#!/usr/bin/env bash
# Fizzbuzz

for ((n=1; n<=100; n++)); do
  if ! (( n % 3 )) && ! (( n % 5 )); then
    echo "FizzBuzz"
  elif ! (( n % 3 )); then
    echo "Fizz"
  elif ! (( n % 5 )); then
    echo "Buzz"
  else
    echo "$n"
  fi
done
